#!/bin/sh
#
# start / stop mpdas daemon

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/mpdas
PID=/var/run/mpdas/mpdas.pid

case $1 in
    start) "$SSD" --start --background --pidfile "$PID" --exec "$PROG";;
    stop)  "$SSD" --stop --retry 10 --pidfile "$PID";;
    restart)
        "$0" stop
        "$0" start
        ;;
    status)
        "$SSD" --status --pidfile "$PID"

        case $? in
            3) echo "$PROG is not running";;
            0) echo "$PROG is running with pid $(cat "$PID")";;
            1) echo "$PROG is not running but the pid file $PID exists";;
            4) echo "unable to determine the program status"
        esac
        ;;
    *) echo "usage : $0 [start|stop|restart|status]"
esac
